name: IridiumMobCoins
version: ${version}
description: MobCoins Redifined
main: com.iridium.iridiummobcoins.IridiumMobCoins
api-version: '1.13'
author: Peaches_MLG
commands:
  IridiumMobCoins:
    aliases: [ "mobcoins", "mc" ]
    description: Main plugin command
